### ISSUE TITLE
Question: Different between rippled API, XRP API and Data API?

### ISSUE THREAD

**Issue by gutenye** [ripple/xrp-api#4]
Can anyone help me understand the difference between rippled API, XRP API and Data API? Thanks.

**Comment by dvilelaf** [comment]
- **rippled API**: a websocket api to communicate with the XRPL. This is the complete implementation, so it is more complex.
- **Data API**: a REST api just to gather some data from the XRPL over HTTP (not sending transactions). 
- **XRP-API**: a simple REST-like api to send payments and get basic info about the XRPL. Here you have you own api server running in your computer. Its simpler, but limited to a few functionalities.

**Comment by gutenye** [comment]
Thanks.
